.github/workflows/check-sonarcloud-on-push-to-branch.yml, .github/workflows/check-sonarcloud-on-push.yml, sonar-project.properties
Workflow and configuration for sonarcloud added.
https://ticketsystem.dbildungscloud.de/browse/DBP-332
=> DBP-332-sonarcloud

sonar-project.properties
=> SPSH-228 configure code coverage exceptions

pages/email4teacher.page.ts, pages/itslearning.page.ts, pages/menue.page.ts, pages/start.page.ts, playwright.config.ts, tests/workflow.spec.ts
=> Spsh 265 Angebote per Link öffnen

.github/workflows/playwright.yml, README.md
Change action to:
- add workflow_call event trigger
- add optional input variable frontendHostname for workflow dispatch
- add optional env variable FRONTEND_URL for job "test" which defaults to "helm.dev.spsh.dbildungsplattform.de"
=> Dbp 618 ausfuehren der playwright tests fuer beliebige branches

.github/workflows/auto-tag-release.yml
=> DBP-681-automate-generation-of-tags

docs/developer-notes.md, pages/admin/PersonCreationView.page.ts, tests/Person.spec.ts
Neuer Testfall Benutzer anlegen:
- Neuen Benutzer anlegen
- Der Neue Benutzer meldet sich am Portal an mit dem Einmalpasswort
- Der Benutzer vergibt ein neues Passwort
=> Spsh 508 neuen benutzer anlegen

tests/api.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-512
Spike: Playwright für die Nutzung der API(Testdatenerstellung) vorbereiten
Ich habe einen Schnittstellentest mit einem GET und POST personen erstellt.
=> Spsh 512 spike api

.github/workflows/schedule_dev.yml, pages/LoginView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Person.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-509
- Neuer Testfall "Ergebnisliste Benutzer auf Vollständigkeit pruefen"
-  Schedule Alle Tests fuer main
=> SPSH 509 Testfall Ergebnisliste Benutzer auf Vollstaendigkeit prüfen fertig

.github/workflows/playwright.yml
Im Workflow playwright.yml  habe ich den playwright_branch input parameter hinzugefügt.I added  determine_playwright_branch job to determine the Playwright test branch
=> Dbp 757 playwright tests

pages/MenuBar.page.ts, pages/admin/RolleCreationView.page.ts, pages/admin/SchuleCreationView.page.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/login.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
Test for schule creation
https://ticketsystem.dbildungscloud.de/browse/SPSH-633
requires: https://github.com/dBildungsplattform/schulportal-client/pull/155
=> spsh 633 schule creation test

.github/workflows/manuell_staging.yml
https://ticketsystem.dbildungscloud.de/browse/SPSH-725
=> SPSH-725 fixed wrong quotation marks

README.md, playwright.config.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/login.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-697
- Neuer Testfall Suchfunktion Ergebnisliste Benutzer
- README überarbeitet
- Refactoring
=> Spsh 697 suchfunktion ergebnisliste

tests/Person.spec.ts, tests/Rolle.spec.ts
=> renamed to Land Schleswig Holstein

pages/MenuBar.page.ts, pages/admin/KlasseCreationView.page.ts, pages/admin/KlasseManagementView.page.ts, tests/Klasse.spec.ts
SPSH-686
https://ticketsystem.dbildungscloud.de/browse/SPSH-686
- Neuer Testfall Klasse anlegen
- Neuer Testfall Ergebnisliste Klasse prüfen
=> spsh 686 Neue Testfälle Klassen fertig

pages/admin/PersonCreationView.page.ts
changed locator to fix playwright tests
https://ticketsystem.dbildungscloud.de/browse/SPSH-784
https://github.com/dBildungsplattform/schulportal-client/pull/182
=> spsh 784 fixed combobox clear selector

pages/admin/RolleCreationView.page.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-708
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/539
https://github.com/dBildungsplattform/schulportal-client/pull/179
=> spsh 708 fixed test id

pages/admin/KlasseManagementView.page.ts, pages/admin/PersonCreationView.page.ts, tests/Person.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-888
=> SPSH-888 Test Personen und Test Klassen angepasst

tests/Klasse.spec.ts, tests/Person.spec.ts, tests/Rolle.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-903
=> Fix locators

.github/workflows/playwright.yml, .github/workflows/schedule_dev.yml, .github/workflows/schedule_staging.yml, .github/workflows/schedule_test.yml
=> DBP-791 playwright rocketchat notification

pages/admin/KlasseCreationView.page.ts
TestID für button_KlasseAnlegen geändert.
=> fix testid button_KlasseAnlegen

playwright.config.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-974
=> SPSH-974 config angepasst, maxFailures=3, retires=1

playwright.config.ts, tests/Klasse.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-994
=> SPSH-994 fix Filter setzen Ergebnisliste Klasse

pages/Cards/ItsLearning.page.ts, pages/StartView.page.ts
=> Update itslearning url

pages/admin/PersonCreationView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Person.spec.ts, tests/Rolle.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-811
https://github.com/dBildungsplattform/schulportal-client/pull/218
=> spsh 811 added kopersnummer to lehrkraft creation

tests/Person.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1033
https://github.com/dBildungsplattform/schulportal-client/pull/229
=> spsh 1033 removed klasse from lehrer tests

base/api/testHelperPerson.page.ts
Anpassung des Body/Payload fürs Anlegen der Personenkontexte, damit die folgenden Testfällae gefixt werden können:
- Testfälle für Schulportal Administration: Prüfen, dass die Schulportal-Administration Kachel nicht sichtbar ist für Lehrkräfte
- Testfälle für Schulportal Administration: Prüfen, dass die Schulportal-Administration Kachel nicht sichtbar ist für Schüler
- Testfälle für Schulportal Administration: Prüfen, dass die Schulportal-Administration Kachel sichtbar ist für Schuladmins
- Testfälle für die Administration von Personen: Mehere Benutzer hintereinander anlegen in der Rolle Landesadmin für die Rollenarten SuS und LEHR und die Bestätigungsseiten vollständig prüfen
- Testfälle für die Administration von Schulen: Eine Schule anlegen als Schuladmin und die Bestätigungsseite …
=> SPSH-1080: Testfälle fürs Anlegen der Personenkontexte über den Endpunkt Personenkontext-Workflow fixen

LICENSE, package.json
=> Dbp 952 add license file

pages/StartView.page.ts
=> SPSH-1145 Change locator of itslearning

.env.dev, .env.devTest, .env.local, .env.stage, .env.staging, .github/workflows/manuell_staging.yml, .github/workflows/schedule_dev.yml, .github/workflows/schedule_staging.yml, pages/Cards/Calendar.page.ts, pages/Cards/Directory.page.ts, pages/StartView.page.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1043
Kacheln email, Adressbuch, Kalender werden im Test angesprochen in der Umgebung dev
=> Spsh 1043 fix angebote per link oeffnen

package-lock.json, package.json
https://ticketsystem.dbildungscloud.de/browse/SPSH-???
=> Update Version to current dev 0.6.0

playwright.config.ts
tracelog enabled
https://ticketsystem.dbildungscloud.de/browse/SPSH-1181
=> tracelog enabled

base/api/testHelperRolle.page.ts
added version to rolle methods
https://ticketsystem.dbildungscloud.de/browse/SPSH-1098
https://github.com/dBildungsplattform/dbildungs-iam-server/pull/674
https://github.com/dBildungsplattform/schulportal-client/pull/259
=> spsh 1098 optimistic locking for rollen

base/testHelperDeleteTestdata.ts, sonar-project.properties, tests/Klasse.spec.ts, tests/Person.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1115
Die Tests dürfen keine Testdaten hinterlassen.
Das Abräumen der erstellten Testdaten erfolgt im afterEach-Block in den Tests.
=> Spsh-1115 refactoring delete objects after each

tests/Person.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1181
Auf der Bestätigungsseite Rollenanlage werden die Daten jetzt via expect geprüft da diese anscheinend asynchron geladen werden
=> SPSH-1181 added expections for page role-confirmation

pages/Header.page.ts, pages/LoginView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Klasse.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/login.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1211
Kleinere Optimierungen damit die Tests stabiler laufen
=> Spsh 1211 fix logout

README.md, pages/admin/PersonDetailsView.page.ts, tests/Person.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1021
https://github.com/dBildungsplattform/schulportal-client/pull/233
=> SPSH-1021 fixed selector

base/api/testHelperPerson.page.ts, base/roles.ts, sonar-project.properties, tests/Person.spec.ts, tests/Profile.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/workflow.spec.ts
=> SPSH-1163 rename roles

tests/Profile.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1301
Disabled checks for 2FA in profile tests
=> SPSH-1301 fix

docs/struktur.md
https://ticketsystem.dbildungscloud.de/browse/SPSH-1326
=> Strukturbeschreiung PW-Tests

.eslintrc.cjs, .prettierrc.json, base/api/testHelperOrganisation.page.ts, base/api/testHelperPerson.page.ts, base/api/testHelperRolle.page.ts, base/api/testHelperServiceprovider.page.ts, package.json, pages/MenuBar.page.ts, pages/admin/KlasseManagementView.page.ts, pages/admin/PersonManagementView.page.ts, pages/admin/RolleCreationConfirm.page.ts, pages/admin/RolleManagementView.page.ts, playwright.config.ts, tests/Klasse.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/login.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1059
Basisregeln eingeführt für eslint.
=> Spsh 1059 config eslint

tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1405
=> SPSH-1405 fix password test

base/api/testHelperPerson.page.ts, base/api/testHelperServiceprovider.page.ts, base/testHelperGenerateTestdataNames.ts, package-lock.json, package.json, playwright.config.ts, tests/Klasse.spec.ts, tests/Person.spec.ts, tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1391
Diverse flaky tests gefixed
=> Spsh 1391 fix profile tests

tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1415
=> Spsh 1415 fix password test

base/api/testHelperPerson.page.ts, base/testHelperGenerateTestdataNames.ts, tests/Person.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1481
=> SPSH-1481 fix tests

pages/StartView.page.ts, tests/Import.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1562
=> SPSH-1562 fixed logout test

pages/admin/PersonDetailsView.page.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1542
https://github.com/dBildungsplattform/schulportal-client/pull/370
=> Spsh 1542 fixed locator for pw reset dialog

pages/admin/PersonDetailsView.page.ts, tests/PersonBearbeiten.spec.ts
=> SPSH-1356 Add tests for Befristung selection

tests/Person.spec.ts
=> SPSH-1693: fix broken import

pages/MenuBar.page.ts, pages/admin/RolleManagementView.page.ts, tests/Rolle.spec.ts
Bumping version in the application results in some changes in behavior, which cause some PW-tests to fail.
=> SPSH-1176: Version Bump

.github/workflows/manuell_staging.yml, .github/workflows/playwright.yml, .github/workflows/schedule_dev.yml, .github/workflows/schedule_dev_crossBrowser_Firefox.yml, .github/workflows/schedule_staging.yml
=> DBP-1261 Use upload-artifact@v4

.github/workflows/check-sonarcloud-on-push.yml, pages/ProfileView.page.ts
changed a locator to match changes in frontend
https://ticketsystem.dbildungscloud.de/browse/SPSH-1200
https://github.com/dBildungsplattform/schulportal-client/pull/416
=> SPSH-1200 changes for coverage optimization

base/api/testHelperOrganisation.page.ts, base/api/testHelperPerson.page.ts, base/klassen.ts, pages/Header.page.ts, pages/MenuBar.page.ts, pages/StartView.page.ts, pages/admin/KlasseDetailsView.page.ts, pages/admin/KlasseManagementView.page.ts, tests/Klasse.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/Profile.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-963
- 6 Neue Testfälle für das Löschen von Klassen
=> Spsh 963 050225

README.md, base/api/testHelperPerson.page.ts, base/berechtigungen.ts, pages/Header.page.ts, pages/LoginView.page.ts, pages/ProfileView.page.ts, pages/StartView.page.ts, pages/admin/PersonDetailsView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Import.spec.ts, tests/Klasse.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/TwoFactorAuthentication.spec.ts, tests/login.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-966
- Neuer Testfall: Passwort setzen über das Benutzerprofil- 
- Refactoring
=> Spsh 966 set pw via profil

pages/StartView.page.ts, pages/admin/PersonCreationView.page.ts, pages/admin/PersonDetailsView.page.ts, tests/Person.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1912
1) Der Testfall "Eine Lehrkraft anlegen in der Rolle Landesadmin und die Bestätigungsseite vollständig prüfen" in Person.spec wird in erweitert um einen zusätzlichen Step damit der Sprung zur Gesamtuebersicht getestet wird.
2) Camel case gefixed
=> Spsh 1912 nach Benutzeranlage Gesamtuebersicht oeffnen

base/api/testHelperPerson.page.ts, pages/Header.page.ts, pages/StartView.page.ts, tests/Import.spec.ts, tests/Klasse.spec.ts, tests/MenuBar.spec.ts, tests/Person.spec.ts, tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/Schule.spec.ts, tests/SchulportalAdministration.spec.ts, tests/TwoFactorAuthentication.spec.ts, tests/login.spec.ts, tests/logoff.spec.ts, tests/workflow.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-1809
1. Neuer Parameter logoutViaStartPage in Header.page.ts und allen spec files
2. Die ersten beiden Testfälle in Klasse.spec.ts benutzen den logout ohne den Umweg über die Startseite, die anderen Testfälle müssen später schrittweise umgestellt/angepasst werden
3. Diverse type annotations in den spec files gefixed
=> SPSH-1809 Neuer Parameter für das logout

elements/ComboBox.ts, pages/admin/KlasseDetailsView.page.ts, tests/Klasse.spec.ts
- fix selectors
- remove work-around in combobox
=> SPSH-1799: Schulfiter überarbeiten

base/api/testHelperOrganisation.page.ts, base/api/testHelperRolle.page.ts, base/testHelperDeleteTestdata.ts, elements/ComboBox.ts, pages/StartView.page.ts, pages/admin/KlasseCreationView.page.ts, pages/admin/KlasseManagementView.page.ts, pages/admin/PersonCreationView.page.ts, pages/admin/PersonDetailsView.page.ts, pages/admin/PersonImportView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Klasse.spec.ts, tests/PersonBearbeiten.spec.ts
- Some refactoring to make tests more robust (mostly wait for loading)
- Add cleanup for klassen in tests where they should be deleted. If the test failed, the data was left and could cause issues for other tests. The api-helper for deletion was slightly changed so it can handle deletion of objects that don't exist anymore.
=> SPSH-2033: fix flakyness in Klasse-Tests

README.md, elements/ComboBox.ts, tests/Person.spec.ts, tests/SchulportalAdministration.spec.ts
https://ticketsystem.dbildungscloud.de/browse/SPSH-2083
=> SPSH-2083 fix test: Einen Benutzer mit der Rolle Landesadmin anlegen

pages/MenuBar.page.ts, pages/admin/PersonManagementView.page.ts, tests/Person.spec.ts
=> SPSH-2020: fix some flakyness

elements/ComboBox.ts, pages/MenuBar.page.ts, pages/StartView.page.ts, pages/admin/KlasseCreationView.page.ts, pages/admin/KlasseManagementView.page.ts, pages/admin/PersonCreationView.page.ts, pages/admin/PersonDetailsView.page.ts, pages/admin/PersonManagementView.page.ts, tests/Klasse.spec.ts, tests/Person.spec.ts, tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts, tests/Rolle.spec.ts, tests/SchulportalAdministration.spec.ts
- updated some selectors
- general changes that hopefully reduce flakyness
=> SPSH-1919: Klassenfilter

tests/PersonBearbeiten.spec.ts, tests/Profile.spec.ts
=> SPSH-2257: update text

tests/Rolle.spec.ts
we skip a useless test to make playwright less flaky
https://ticketsystem.dbildungscloud.de/browse/SPSH-2163
=> SPSH 2163 PW tests sind flaky
